"""empty message

Revision ID: cafe81e35b2d
Revises: 3f2cc96dfa5d
Create Date: 2020-02-13 01:41:08.638140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cafe81e35b2d'
down_revision = '3f2cc96dfa5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lawyer', sa.Column('kind', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('kind', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'kind')
    op.drop_column('lawyer', 'kind')
    # ### end Alembic commands ###
